# Functions to modify URLs
# Emilio Lehoucq
# This script uses code generated by ChatGPT and GitHub Copilot

# Importing libraries

from urllib.parse import urlparse

# Defining function to modify URLs for schooljobs.com

def modify_url_school_jobs(input_url):
    # Parse the input URL
    parsed_url = urlparse(input_url)
    # Get the path components
    path_components = parsed_url.path.split('/')
    # Find the index of the job ID in the path
    job_id_index = path_components.index('jobs') + 1
    # Modify the path
    path_components_new = path_components[:job_id_index] + ['newprint', path_components[job_id_index]] 
    # Create a new URL with the modified path
    modified_url = parsed_url.scheme + '://' + parsed_url.netloc + '/'.join(path_components_new)
    return modified_url

if __name__ == '__main__':
    print("url_modifiers_github_actions.py is being run as the main script.")