name: Run Scraping Google Sheet Script

on:
  schedule:
    - cron: '0 3 * * *' # 3am UTC (10 pm central)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      run: |
        python scraping_google_sheet.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
    
    - name: Check for changes in data.csv
      id: check_changes
      run: |
        git fetch origin
        if git diff --quiet origin/main data.csv; then
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "changes=true" >> $GITHUB_ENV
        fi
    
    - name: Commit and Push changes
      if: env.changes == 'true'
      run: |
        git add data.csv
        git commit -m "Replaced existing data file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

